### ISSUE TITLE
sdcdb调试器不能用

### ISSUE THREAD

**Issue by dawendiguo** [hungtcs-lab/8051-examples#4]
系统是fedora 32, sdcc是4.0,  sdcdb是0.9
编译有加--debug, sdcdb 也可以进。
```bash
sdcdb main.ihx
(sdcdb) break 5
No line 4 or after in file "main.c"..
```
list命令可以用，break就有问题了。要是break 函数名就直接段错误了。

想问问你用的sdcc有这问题吗？是那个版本的？sdcc貌似都找不到最新的。

**Comment by hungtcs** [comment]
最新版的sdcc可以从sdcc官网下载源码编译安装，sdcc官网是：http://sdcc.sourceforge.net/
源码编译安装教程：https://blog.hungtcs.top/2020/05/22/25-sdcc%E7%BC%96%E8%AF%91%E5%99%A8%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4/
