### ISSUE TITLE
想借用下您的代码，是否可以

### ISSUE THREAD

**Issue by Jiangshan00001** [hungtcs-lab/8051-examples#5]
我写了一个开源的单片机c编译器。
想做一个测试。
看到您这个项目里，有好多的示例程序。
想用于c编译器的测试例子里。
不知道是否可以？

**Comment by Jiangshan00001** [comment]
https://github.com/Jiangshan00001/MZC8051

**Comment by hungtcs** [comment]
@Jiangshan00001 当然可以，在许可证允许范围内可随意使用
