### ISSUE TITLE
The programing comment style

### ISSUE THREAD

**Issue by yaodehaung** [hungtcs-lab/8051-examples#6]
When I compile the program, I need the c99 flag to solve the problem of the exception of // annotations. 
You can specify in the README file that you want to use the c99 flag to compile the code

**Comment by hungtcs** [comment]
Hi, this repository is only working with sdcc compiler, as far as I know, this flag is not needed.

my sdcc version is 
```
SDCC : mcs51/z80/z180/r2k/r2ka/r3ka/gbz80/tlcs90/ez80_z80/z80n/ds390/pic16/pic14/TININative/ds400/hc08/s08/stm8/pdk13/pdk14/pdk15 4.1.0 #12072 (Mac OS X ppc)
published under GNU General Public License (GPL)
```

> SDCC is a retargettable, optimizing Standard C (ANSI C89, ISO **C99**, ISO C11) compiler suite that targets the Intel MCS51 based microprocessors (8031, 8032, 8051, 8052, etc.), Maxim (formerly Dallas) DS80C390 variants, Freescale (formerly Motorola) HC08 based (hc08, s08), Zilog Z80 based MCUs (z80, z180, gbz80, Rabbit 2000/3000, Rabbit 3000A, TLCS-90), Padauk (pdk14, pdk15) and STMicroelectronics STM8. Work is in progress on supporting the Padauk pdk13 target; Microchip PIC16 and PIC18 targets are unmaintained. SDCC can be retargeted for other microprocessors.
